image:
  file: .devcontainer/Dockerfile
vscode:
  extensions:
    - mhutchie.git-graph
    - redhat.java
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
