version: "3"
volumes:
  home:
services:
  dev:
    build:
      context: "https://github.com/sebfisch/docker-java-dev.git#latest"
      # Adjust the build args to reflect your local setup
      args:
        JAVA_VERSION: 11
        UID: 501
        GID: 501
    hostname: java-dev
    command: tmux -u new -s java-fun-code
    environment:
      # Adjust to reflect your own timezone
      - TZ=Europe/Berlin
        # The following line disables class data sharing for the JVM
        # which leads to a warning message on some architectures.
        # - JAVA_OPTIONS=-Xshare:off
    volumes:
      - home:/home
      - ~/.ssh:/home/me/.ssh/:ro
      - .:/home/me/java-fun-code
    working_dir: /home/me/java-fun-code
